name: Cross-Platform Build

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up MSYS2 (for MinGW on Windows)
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            git
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake

      - name: Configure CMake (Windows)
        if: matrix.os == 'windows-latest'
        shell: msys2 {0}
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=ON

      - name: Configure CMake (Linux/macOS)
        if: matrix.os != 'windows-latest'
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=ON

      - name: Build with CMake (Windows)
        if: matrix.os == 'windows-latest'
        shell: msys2 {0}
        run: cmake --build build --config Release --parallel

      - name: Build with CMake (Linux/macOS)
        if: matrix.os != 'windows-latest'
        run: cmake --build build --config Release --parallel

      - name: Archive examples
        uses: actions/upload-artifact@v4
        with:
          name: examples-${{ matrix.os }}
          path: build/bin/