name: Cross-Platform Build

on:
  push:
    branches: ['**']
    tags: ['**']
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Linux (Clang)"
            artifact_name: examples-linux-clang

          - name: "Windows (MinGW Cross-Compile)"
            artifact_name: examples-windows-mingw

    runs-on: ubuntu-latest

    env:
      CC: ${{ contains(matrix.name, 'Clang') && 'clang' || 'gcc' }}
      CXX: ${{ contains(matrix.name, 'Clang') && 'clang++' || 'g++' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          if [ "${{ matrix.name }}" == "Linux (Clang)" ]; then
            sudo apt-get install -y clang
          elif [ "${{ matrix.name }}" == "Windows (MinGW Cross-Compile)" ]; then
            sudo apt-get install -y mingw-w64
          fi

      - name: Configure CMake
        run: |
          if [ "${{ matrix.name }}" == "Windows (MinGW Cross-Compile)" ]; then
            cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=cmake/windows-mingw-toolchain.cmake -DBUILD_EXAMPLES=ON
          else
            cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=ON
          fi

      - name: Build with CMake
        run: cmake --build build --config Release --parallel

      - name: Archive examples
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: build/bin/